"""Six Nations Picker — model layer (Strategy C).

Predict the API-measurable components -> score them with the frozen modern
formula (`build_targets.score_components`) -> add a forward-chained latent
baseline (`build_targets._fit_latent`) -> rank for selection.

The extraction stores (`data/model_player_match.csv`, `data/model_targets.csv`)
are READ-ONLY inputs and are never regenerated by this package.
"""
from __future__ import annotations
